@rootURL = http://localhost:5001

GET {{rootURL}}/api/Products/
Accept: application/json

###

POST {{rootURL}}/api/Products/
Content-Type: application/json
{
  "id": 0,
  "name": "string",
  "quantity": 3,
  "price": 0
}
###
Post {{rootURL}}/api/books
Content-Type: application/json
{